create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.candidates (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories(id) on delete cascade,
  name text not null,
  position text not null default '',
  image_url text not null default '',
  color_index integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  voter_hash text not null,
  category_id bigint not null references public.categories(id) on delete cascade,
  candidate_id bigint not null references public.candidates(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint votes_unique_voter_category unique (voter_hash, category_id)
);

create index if not exists categories_sort_order_idx on public.categories (sort_order, id);
create index if not exists candidates_category_id_idx on public.candidates (category_id, id);
create index if not exists votes_category_id_idx on public.votes (category_id, id);
create index if not exists votes_candidate_id_idx on public.votes (candidate_id, id);

alter table public.categories enable row level security;
alter table public.candidates enable row level security;
alter table public.votes enable row level security;

create policy "Public read categories"
  on public.categories
  for select
  using (true);

create policy "Public read candidates"
  on public.candidates
  for select
  using (true);

create policy "Public read votes"
  on public.votes
  for select
  using (true);

create policy "Public insert votes"
  on public.votes
  for insert
  with check (char_length(voter_hash) > 0);

insert into storage.buckets (id, name, public)
values ('candidate-media', 'candidate-media', true)
on conflict (id) do nothing;

create policy "Public read candidate media"
  on storage.objects
  for select
  using (bucket_id = 'candidate-media');

create policy "Public upload candidate media"
  on storage.objects
  for insert
  with check (bucket_id = 'candidate-media');
